### ISSUE TITLE
Document maintenance/compatibility of python vs go implementation

### ISSUE THREAD

**Issue by sconover** [dropbox/mypy-protobuf#10]
I'm curious about (a) what the decisionmaking process / motivation was behind the creation of each implementation (including motivation for language selection), and (b) how you see the overall tech investment/support for each of these playing out over time. Will you be making an effort to keep one implementation functionally and qualitatively equivalent to the other?

If it's possible, could you also please characterize how each of these implementations is used inside dropbox?

**Comment by sconover** [comment]
Very good to know, thank you for the explanation.

**Comment by nipunn1313** [comment]
I added some commentary to the README on this point.

In the past week, I've spent some time leveling up the testing and support for the python implementation. #11 is still open to get better compatibility.
