### ISSUE TITLE
FromString argument type doesn't work for Python2

### ISSUE THREAD

**Issue by mikolajz** [dropbox/mypy-protobuf#100]
As I understand, the typeshed definition is used for the definition of the base Message class and a commit in October ([1]) changed the argument of FromString from "Any" to "bytes" in Python3 and a Union of "bytes", "buffer" and "unicode"(strange) in Python 2. mypy-protobuf emits bytes as the type of the argument of FromString, thus in Python2 we get lots of errors about the argument type of the subclass being more narrow that the superclass.

The code in the attachment seems to make it work. Will you want to include such a fix?

[mypy-diff.txt](https://github.com/dropbox/mypy-protobuf/files/4118583/mypy-diff.txt)

[1] https://github.com/python/typeshed/commit/036abc7fda9290e29d978d62b00e03b67a2a6fd1#diff-2492d636b6705e307c9cb32d169f3614

**Comment by nipunn1313** [comment]
This sounds reasonable! Please go ahead and send a pull request with a test case.
The testsuite of mypy-protobuf should run against py2 and py3

If you can do the following it would be excellent
1) Add some code to https://github.com/dropbox/mypy-protobuf/blob/master/test/test_generated_mypy.py which would fail mypy and confirm that the testsuite fails (it runs mypy)
2) Apply your fix
3) Confirm that the test now passes

And put that all into a PR - would be happy to take it. Thanks for catching!

**Comment by mikolajz** [comment]
It ended up being a bit more complicated and larger, but I now have a PR - https://github.com/dropbox/mypy-protobuf/pull/101 .

**Comment by nipunn1313** [comment]
Closed by #101 ! Thanks!

**Comment by nipunn1313** [comment]
Normally I wait for a conglomeration of updates before cutting a build, but the repo is relatively low on activity - so I'd be willing to cut a build on request if you need it. Let me know.

**Comment by mikolajz** [comment]
I was to ask about the release. Cutting it now would be great, as we will
just switch to it and won't need to patch the sources in our tools.
Mikołaj
