### ISSUE TITLE
Add tests for go/python output equivalency

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/mypy-protobuf#11]
For existing places in which they are not equivalent, discuss/determine which behavior makes sense.

**Comment by drather19** [comment]
Besides the concern raised in #12, I've noticed a few other differences:
- Differences in the package imports in the generated Python code
- Usage of bytes vs. str in the argument to FromString()

**Comment by dzbarsky** [comment]
I believe `FromString` should take in `bytes` (the go version currently uses `str` because it was only used for python2 where they are equivalent). @nipunn1313 if you agree i can update it?

**Comment by nipunn1313** [comment]
From https://developers.google.com/protocol-buffers/docs/reference/python-generated
```FromString(s): Returns a new message instance deserialized from the given string.```

So `s` is serialized, and should be `s: bytes`. I am in support.
Typically, in mypy for compatibility, we should strive to use either `typing.Text` or `bytes`, but never `str`, because `str` changed meaning across python versions.

**Comment by nipunn1313** [comment]
planning on deprecating the go version instead!

**Comment by nipunn1313** [comment]
dropped go support!
