### ISSUE TITLE
New version on PyPI?

### ISSUE THREAD

**Issue by forestbelton** [dropbox/mypy-protobuf#115]
Hi,

I was wondering when a new version would be released on PyPI. We're very much looking forward to some of the changes introduced since last release, but have had some trouble specifying a git SHA in our `requirements.txt` to point at a non-PyPI verison. Thanks so much!

**Comment by nipunn1313** [comment]
Bumped to 1.20!
Sorry about that.

Hope you're doing well!

**Comment by forestbelton** [comment]
Sorry for the late reply - thank you for the release!
