### ISSUE TITLE
module.DESCRIPTOR is not supported

### ISSUE THREAD

**Issue by awbraunstein** [dropbox/mypy-protobuf#117]
When attempting to access the `DESCRIPTOR` attribute on a protobuf module, i get a `Module has no attribute "DESCRIPTOR"` error. From looking at the code, it seems we generate a `DESCRIPTOR` attributer on messages and enums, but not one for the module itself.

This should probably be generated, since it is valid syntax and is the correct way to access the `FileDescriptor` for the file that corresponds to the current pb2.py file.

**Comment by nipunn1313** [comment]
Yep - great point! Thanks for the report.

Could probably do something like

```
pkg_writer.write_module_attributes()
```

here

https://github.com/dropbox/mypy-protobuf/blob/master/python/mypy_protobuf.py#L606

And implement some kind of

```
def write_module_attributes():
    l("DESCRIPTOR: {} = ...", self._import("google.protobuf.descriptor", FileDescriptor")
```

Does that sound right? By running the testsuite, it should update the expected pyi files (eg https://github.com/dropbox/mypy-protobuf/blob/master/test/proto/test3_pb2.pyi.expected).

Would you be interested in submitting a PR?
Thanks

**Comment by nipunn1313** [comment]
Had some extra cycles and put up a PR (#123)

Hope you're holding up well through the pandemic
