### ISSUE TITLE
Message enum attributes have incorrect type annotations

### ISSUE THREAD

**Issue by wmdrichards** [dropbox/mypy-protobuf#118]
Running mypy-protobuf on the following proto definition
```
syntax = "proto3";

enum Enum {
  OK = 0;
  NOT_OK = 1;
}

message Message {
  Enum enum = 1;
}
```
Produces a .pyi file with
```
class Enum(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'Enum': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['Enum']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Enum']]: ...
    OK = typing___cast('Enum', 0)
    NOT_OK = typing___cast('Enum', 1)
OK = typing___cast('Enum', 0)
NOT_OK = typing___cast('Enum', 1)
global___Enum = Enum

class Message(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    enum = ... # type: global___Enum
```
which suggests to mypy that the enum attributes exist on the enum object e.g. that  `Message().enum.OK` is valid. In reality the generated code (using grpc_tools) has `type(Message().enum) == int`, which obviously doesn't have the `OK` attributes (or `keys`, `values` etc) and `Message().enum.OK` fails at runtime

**Comment by nipunn1313** [comment]
Yep - this is a known shortcoming of the area - check out #84
May have some time to take another stab at it improving it. Thanks for the report!

**Comment by nipunn1313** [comment]
Was able to fix this one up!

Note that this approach takes the opinionated approach of returning a NewType over the int

If you try to construct a message passing an int to the constructor, it will fail, expecting to be wrapped in the NewType (in your case, `global__EnumValue`). This is probably for the best!

**Comment by wmdrichards** [comment]
Thanks for the quick fix! When can we expect a version bump? Excited to start using the new functionality

**Comment by nipunn1313** [comment]
I have one more fix I'd like to get in before bumping the version, so hopefully I should be able to get to it by the end of the week!

**Comment by pcorpet** [comment]
FYI this is breaking our type checks, and it's not as simple as replacing MyEnum by MyEnumValue because MyEnumValue exists only during type checking. I'm converting all those types to string `MyEnum` => `'MyEnumValue'`

**Comment by nipunn1313** [comment]
Ah shoot!
This should be coverable as an issue by our test suite but was missed.

The typing only exists at mypy time which makes this tricky. String
'myenumvalue' for the type should work.

I'm not sure whether this NewType wrapper type around int is worth this
ergonomic hassle.

Pcorpet - does the wrapper enum value type add sufficient typechecking
value for you over a plain int?

Any ideas on how to get it to work in a way that's ergonomic - such that
the NewType is available to python as well? Probably would involve
integration with upstream protoc project

--Nipunn

**Comment by pcorpet** [comment]
The string totally works for us. And yes the previous change (having wrapper around int) helped us uncover some serious mistakes, so thank you. Having it as a different type than the enum class isn't necessary for us, but if it's useful for others like @wmdrichards we totally get it.

I was leaving a note for others to quickly see what to change in their code. I don't see any easy way to fix it otherwise apart from changing the protobuf python bindings themselves.
