### ISSUE TITLE
Python version doesn't treat maps the same way as the Go version

### ISSUE THREAD

**Issue by drather19** [dropbox/mypy-protobuf#12]
The generated stubs in the Python version emit maps as RepeatedScalarFieldContainer types rather than as MutableMapping types as the Go version does. The latter approach (Go) seems to be correct and working.

**Comment by drather19** [comment]
More specifically, the logic [here in Go](https://github.com/dropbox/mypy-protobuf/blob/master/go/src/protoc-gen-mypy/main.go#L508) seems to be missing from [here in Python](https://github.com/dropbox/mypy-protobuf/blob/master/python/protoc-gen-mypy#L150).

**Comment by nipunn1313** [comment]
Yep this looks correct. @drather19 - do you believe this was fixed in #13? (It looks to be so - but you have additional context)

**Comment by drather19** [comment]
Yes, I believe we can close this issue now.

**Comment by nipunn1313** [comment]
Thanks! 👍
