### ISSUE TITLE
google-stubs/protobuf/well_known_types and others

### ISSUE THREAD

**Issue by Evgenus** [dropbox/mypy-protobuf#135]
- It seems like `RepeatedCompositeFieldContainer` (which is used to wrap all repeated fields) is not iterable for mypy. So all items in loops are infered as Any. 
- Also copying all methods of `Message` class into each message is not the best approach IMO. 
- And there are lots of internal/standart library classes of google.protobuf that could be annotated/stubbed. 

What do you think about creating package with stubs for google.protobuf internal classes?

In that case all generated messages annotations could just inherit base `Message` class (same way as actually generated protobuf messages do)

**Comment by nipunn1313** [comment]
`RepeatedCompositeFieldContainer` should inherit from `Sequence` here in typeshed - which comes for free with mypy

https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/internal/containers.pyi#L38

Shouldn't need to be autogenerated - rather we should be able to get it out of typeshed. I believe that we don't actually copy methods of Message class - only ones that need more special annotations.

**Comment by nipunn1313** [comment]
WKT are supported now!
