### ISSUE TITLE
Map Field does not support get_or_create

### ISSUE THREAD

**Issue by chrislawlor** [dropbox/mypy-protobuf#138]
A protobuf map field provides an API which is slightly different from the normal Python dict (or MutableMapping). Instead, it acts like a `defaultdict`, and allows assignment to undefined keys. It does not, however, allow direct assignment when the field maps to a nested submessage.

Because this behavior is slightly unexpected, when the mapping's value type is a submessage, the map field provides a `get_or_create` method, as an alternative to direct assignment to undefined keys. From https://developers.google.com/protocol-buffers/docs/reference/python-generated#undefined:

> As it may not be immediately obvious to anyone reading your code that m.message_map[10] alone, for example, may create a submessage, we also provide a get_or_create() method that does the same thing but whose name makes the possible message creation more explicit:
```py
# Equivalent to:
#   m.message_map[10]
# but more explicit that the statement might be creating a new
# empty message in the map.
m.message_map.get_or_create(10)
```

Running mypy with stubs created with `mypy-protobuf` against code using map field's `get_or_create` method results in an `attr-defined` error.

### Test Case

```proto
// example.proto
syntax = "proto3";

message Nested {
    string value = 1;
}

message Map {
    map<string, Nested> mapfield = 1;
}
```

Compile using `grpc_tools` and `mypy-protobuf`:

```
python -m grpc_tools.protoc -I=. --python_out=. --mypy_out=. example.proto
```

Inspecting the stub file, we find the type assigned to the `mapfield`:

```py
    @property
    def mapfield(self) -> typing___MutableMapping[typing___Text, type___Nested]: ...
```
This does not include the extra `get_or_create` method supported by protobuf's map field. An example python file using `get_or_create` illustrates the error:

```py
# main.py
from example_pb2 import Map, Nested

m = Map()
mapping_1 = m.mapfield.get_or_create("foo")  # mypy attr-defined error!

nested = m.mapfield["bar"]
nested.value = "bar"
```

#### Mypy output:
```
$ mypy --show-error-codes --pretty main.py
main.py:4: error: "MutableMapping[str, Nested]" has no attribute "get_or_create"  [attr-defined]
    mapping_1 = m.mapfield.get_or_create("foo")  # mypy attr-defined error!
                ^
Found 1 error in 1 file (checked 1 source file)
```

#### Expected output

No mypy errors

### Library versions
```
grpcio==1.30.0
grpcio-tools==1.30.0
mypy==0.782
mypy-extensions==0.4.3
mypy-protobuf==1.23
protobuf==3.12.2
six==1.15.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
```

Python version is 3.8.

## EDIT

The `get_or_create` method is only added when the map field is a map to a nested submessage. The bug still exists, but the example test case originally mapped to a scalar, not a nested message type. I've updated the test case accordingly.

**Comment by nipunn1313** [comment]
Added a test case.

It looks like we should generating one of these:
google.protobuf.internal.containers.ScalarMap
https://github.com/protocolbuffers/protobuf/blob/c6493970296fa5c5b4a81a37248a328579fe9662/python/google/protobuf/internal/containers.py#L458

Those types are not yet in typeshed
https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/internal/containers.pyi#L52

So we have to start there.

**Comment by chrislawlor** [comment]
@nipunn1313 wow that was fast!

I have to apologize though, I had a poor understanding of the map field when I opened this issue. It turns out that `get_or_create` is only available on the `MessageMap` type, not the `ScalarMap`: https://github.com/protocolbuffers/protobuf/blob/c6493970296fa5c5b4a81a37248a328579fe9662/python/google/protobuf/internal/containers.py#L548


I edited the issue to reflect this right around the time that you merged your PR. I suspect we'll want two test cases - a field mapping to simple types (ScalarMap), and a field mapping to message types.

I've created some test cases in a fork:
1. [A negative test, that `get_or_create` on a map to simple types results in error output](https://github.com/chrislawlor/mypy-protobuf/blob/issue-138/map-field-get-or-create/test_negative/negative.py#L102)
2. [A test that uses `get_or_create` on a field mapping to a message type. It's currently lacking any assertions, but does cause the test suite to fail.](https://github.com/chrislawlor/mypy-protobuf/blob/issue-138/map-field-get-or-create/test/test_generated_mypy.py#L313)

These tests are using two [fields added to the Simple1 message](https://github.com/chrislawlor/mypy-protobuf/blob/issue-138/map-field-get-or-create/proto/test/proto/test.proto#L49)

I can open a PR if that's at all helpful

You can see them here

**Comment by nipunn1313** [comment]
Awesome! I'm working on cooking this up real quick.
I'll use your test cases and make sure to cite you as a contributor!

**Comment by nipunn1313** [comment]
@chrislawlor - support for this landed in mypy-protobuf a couple days ago! We're still waiting for a mypy release w/ the latest updates from typeshed so we can release this out w/ the next mypy-protobuf release. mypy 0.790 isn't new enough, so hopefully 0.800 makes the cut at some point in Oct-Nov.
