### ISSUE TITLE
Incorrect assignment to type___{enum.name}?

### ISSUE THREAD

**Issue by henribru** [dropbox/mypy-protobuf#147]
I'll use this enum as an example:
```py
class AccessRoleEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    AccessRoleValue = typing___NewType("AccessRoleValue", builtin___int)
    type___AccessRoleValue = AccessRoleValue
    AccessRole: _AccessRole
    class _AccessRole(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            AccessRoleEnum.AccessRoleValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(AccessRoleEnum.AccessRoleValue, 0)
        UNKNOWN = typing___cast(AccessRoleEnum.AccessRoleValue, 1)
        ADMIN = typing___cast(AccessRoleEnum.AccessRoleValue, 2)
        STANDARD = typing___cast(AccessRoleEnum.AccessRoleValue, 3)
        READ_ONLY = typing___cast(AccessRoleEnum.AccessRoleValue, 4)
        EMAIL_ONLY = typing___cast(AccessRoleEnum.AccessRoleValue, 5)
    UNSPECIFIED = typing___cast(AccessRoleEnum.AccessRoleValue, 0)
    UNKNOWN = typing___cast(AccessRoleEnum.AccessRoleValue, 1)
    ADMIN = typing___cast(AccessRoleEnum.AccessRoleValue, 2)
    STANDARD = typing___cast(AccessRoleEnum.AccessRoleValue, 3)
    READ_ONLY = typing___cast(AccessRoleEnum.AccessRoleValue, 4)
    EMAIL_ONLY = typing___cast(AccessRoleEnum.AccessRoleValue, 5)
    type___AccessRole = AccessRole
    def __init__(self,) -> None: ...
```

Note how `type___AccessRole ` gets set to `AccessRole`. In this context, `AccessRole` refers to an instance attribute in `AccessRoleEnum` of the type `_AccessRole` . This seems odd to me, based on the name I would expect it to refer to the actual type, i.e. the inner class `_AccessRole`. If you use `AccessRoleEnum.type___AccessRole` in a type context with this definition, it causes `Variable [...].AccessRoleEnum.type___AccessRole is not valid as a type` errors. Is it actually meant to be set to `_AccessRole`? I might of course just be misunderstanding something, though.

**Comment by nipunn1313** [comment]
yep! You're right. The important line is
```
    type___AccessRoleValue = AccessRoleValue
```

This line is not necessary
```
    type___AccessRole = AccessRole
```

Notably these `type___` variables are for use within mypy-protobuf. You shouldn't need to access them directly, so public API wise - it's not too big of a deal.

I believe this regression was introduced in #120 - where we added the former line, without removing the latter
I'll put up a fix! Thanks for the report!
