### ISSUE TITLE
Disallow `None` as an argument to constructor for primitives in proto3

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/mypy-protobuf#171]
Currently if you have a message like
```
message MyMessage {
    bool my_bool = 1;
}
```

The autogenerated pyi allows `Optional[bool]` argument to the constructor. In proto3, the wire cannot support a None type, so it would be preferable to type the constructor as `bool` instead. Same for all primitive types.

**Comment by ikonst** [comment]
I think this might create "type errors" in a lot of existing code.

I agree this behavior is inconsistent. Once the object is initialized, you cannot assign `None` to its attributes to unset them -- that causes a TypeError at runtime -- and this applies to both primitive and message types. However, runtime explicitly supports assigning `None` in the initializer and I believe large swaths of code might've been relying on this.

**Comment by nipunn1313** [comment]
Yep - I tried this out quickly in our codebase and it generated
```
Found 1050 errors in 306 files (checked 39104 source files)
```

We haven't shied away from backward incompatible changes in the past, as we've viewed this software as not-yet-stable, though it is getting closer.

Short term idea - might be to provide a flag to preserve the older behavior - in case migrating is challenging.

Perhaps I could release this feature w/ a flag to enable - and prepare for a non-backward-compatible 2.0 release in which the flag is eliminated and you're forced onto the newer, more correct behavior. Perhaps it's coming close to time for a 2.0 release - and increased promise of stability and backward compatibility.

**Comment by ikonst** [comment]
Particularly in the case of initializing message fields, the alternative might be too much.

Much of our code initializes Protobufs as if they were immutable structures:
```python
def get_bar() -> Optional[Bar]: ...

def make_foo() -> Foo:
  return Foo(
    bar=maybe_bar_message(),
  )
```

This would have to be rewritten in a "builder" fashion:
```python
def get_bar() -> Optional[Bar]: ...

def make_foo() -> Foo:
  foo = Foo()
  if bar := maybe_bar_message():
     foo.bar.MergeFrom(bar)
  return foo
```

This churn might be too much for many codebases and frankly for little benefit.

**Comment by ikonst** [comment]
P.S. the Python Protobuf bindings do not produce messages which are immutable structures and such composition (vs. "building") is inefficient due to the copies involved in the implicit `MergeFrom`s when you pass messages in the initializer, but alas a lot of code is built this way

**Comment by nipunn1313** [comment]
I'm not sure I follow the concern. In the above example `Bar` is a `Message` type, which is nullable in proto3 and would be Optional.

However, if you had a `bool` or an `int64`, it's not nullable, and you would not want `Optional[bool]`.

If you have a method like `get_my_bool() -> Optional[bool]` - seems like you already have a problem there and this change would help you identify it.

**Comment by ikonst** [comment]
Gotcha, so it's just for primitive types.

**Comment by nipunn1313** [comment]
It's as specified by proto3 - primitive types are not capable of representing NULL on the wire.
Message types are capable of being nullable, so it would not make sense to eliminate null for that.
