### ISSUE TITLE
python2/3 incompatibility

### ISSUE THREAD

**Issue by nmiculinic** [dropbox/mypy-protobuf#2]
```
Writing mypy to oracle_pb2.pyi
Writing mypy to types_pb2.pyi
Traceback (most recent call last):
  File "/home/lpp/go/src/github.com/nmiculinic/x/.venv/bin/protoc-gen-mypy", line 313, in <module>
    main()
  File "/home/lpp/go/src/github.com/nmiculinic/x/.venv/bin/protoc-gen-mypy", line 310, in main
    sys.stdout.write(output)
TypeError: write() argument must be str, not bytes
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```
python is mapped to: Python 3.6.4

**Comment by gvanrossum** [comment]
We have encountered a similar thing internally. We're trying to see if anyone has fixed it yet. You're also welcome to try and submit a PR if you can figure this out. In the meantime you can use Python 2 as a workaround.

**Comment by gvanrossum** [comment]
@nmiculinic Would you be able to test the supposed patch? (Otherwise it'll be a while before I'll get around to it.)

**Comment by nmiculinic** [comment]
Sure, I'll be able to test it

**Comment by nmiculinic** [comment]
Yes, it appears to be working!
