### ISSUE TITLE
V2 was not tagged

### ISSUE THREAD

**Issue by gitpushdashf** [dropbox/mypy-protobuf#202]
Hi,

Looking forward to some of the latest fixes. However, V2 was never tagged. The link in this commit is broken.

https://github.com/dropbox/mypy-protobuf/commit/73ca10ffb4302414b59397d743ef43e5b2867e06

I do see v2.0 in pypi, however.

Thank you!

**Comment by nipunn1313** [comment]
whoops! Oversight! Tagged and pushed! Thanks.

**Comment by gitpushdashf** [comment]
Great, thank you!
