### ISSUE TITLE
Use UnaryUnaryMultiCallable (and others) instead of function definition in Stubs

### ISSUE THREAD

**Issue by MHDante** [dropbox/mypy-protobuf#209]
Hey! Kudos for releasing V2! It's such a great improvement!

I'm especially fond of the new grpc stubs! they're quite nice.

One thing of note, however is that you are currently using a function definition in service stubs.

However, the  actual implementation is a `MultiCallable`. Using that would allow for passing in additional arguments (like `timeout`), and also access to it's non-calling members (`future` and `with_call`)

See here:

``` Python

# Currenty:
def Generate(self,
    request: global___GenerateRequest,
) -> global___GenerateResponse: ...

# Should Be: 
    Generate : grpc.UnaryUnaryMultiCallable[
        global___GenerateRequest,
        global___GenerateResponse] = ...
```
However, this assumes the use of the grpc-stubs typings (in order for the generics to work). That said, I think it's already a dependency of this module. 

Is there a reason for this decision?

**Comment by MHDante** [comment]
I've suggested the changes in #210

**Comment by nipunn1313** [comment]
CC @Evgenus - who mainly contributed the grpc stubs here. Thoughts on #210 ?

**Comment by Evgenus** [comment]
> I'm especially fond of the new grpc stubs! they're quite nice.

Thanks)


> Is there a reason for this decision?

Actually, no reason. Initially I was not planning to introduce grpc-stubs as a dependency, so I just faked signature with minimal effort required to serve type hints in pycharm.
