### ISSUE TITLE
Pulling a few more active maintainers?

### ISSUE THREAD

**Issue by drather19** [dropbox/mypy-protobuf#21]
Just curious if this repository is going to be actively maintained going forward, since it's gone somewhat stagnant. We definitely appreciate having this utility around (big quality of life improvement when using Python and gRPC/protobuf).

Wondering whether we should either (a.) invite in a few more active maintainers for this repo (i.e., to help review/merge PR's, etc.) or (b.) fork it and move on.

**Comment by dzbarsky** [comment]
Hi, sorry about the silence here. I just went through the PR backlog and reviewed/merged them. The other 2 maintainers are currently on vacation, but I think we are interested in community pull requests.  I also think it would be awesome if more maintainers want to step up, though I'm not too sure if we can add outside maintainers to a project on company github. We can check on this internally and get back to you.

**Comment by nipunn1313** [comment]
Thanks for the kind words.

I'll look into whether additional maintainers could work w/ the Dropbox github org.
In the meantime between guido, dzbarsky, and I, we should be able to go through the PRs.

**Comment by nipunn1313** [comment]
FWIW, maintenance cost will certainly go down once #22 is complete which should accelerate things.
