### ISSUE TITLE
grpc stubs lack annotations for experimental API methods

### ISSUE THREAD

**Issue by gitpushdashf** [dropbox/mypy-protobuf#212]
Just trying out the grpc stub generation, as per #46.

It seems like the gRPC stubs don't have the native gRPC methods added.

For example from grpc .pyi:

```
def GetSomething(self,
    request: global___GetSomethingRequest,
) -> global___GetSomethingResponse: ...
```

However, the grpc .py:

```
@staticmethod
def GetSomething(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
```

Not totally certain if I'm using it correctly, but when using the grpc.pyi files I am getting mypy errors like this, on code where it was definitely working:

```
Unexpected keyword argument "metadata" for "GetSomething" of "GetSomethingStub"
```

Would appreciate any insights you can offer.

Thank you!

**Comment by nipunn1313** [comment]
Yep - sounds like a shortcoming.

grpc stubs were only added last month - w/ only the most basic usage to start.

@Evgenus worked on it and perhaps could comment. I'm not super duper familiar w/ the GRPC generated output.

We'd be happy to take a PR that adds appropriate typing for these extra kwargs w/ unit test showing that such kwargs are accepted at runtime.

**Comment by Evgenus** [comment]
@gitpushdashf @nipunn1313 I'll take a look.

**Comment by gitpushdashf** [comment]
Thank you! I appreciate it.

**Comment by alkasm** [comment]
FWIW: https://github.com/dropbox/mypy-protobuf/pull/210

**Comment by Evgenus** [comment]
@gitpushdashf Hi. Finally, I found some time to investigate. Sorry for the delay.

You are mixing things a bit.

```
def GetSomething(self,
    request: global___GetSomethingRequest,
) -> global___GetSomethingResponse: ...
```

this one was for `<ServiceName>Stub`. Which is the interface of the client. And now/soon (in master) it looks like this:

```
    def __init__(self, channel):

        self.GetSomething = channel.unary_unary(
                '/<module>.<ServiceName>/GetSomething',
                request_serializer=<module>.GetSomethingRequest.SerializeToString,
                response_deserializer=<module>.GetSomethingResponse.FromString,
                )
```

The other part you've mentioned is the implementation of different API. 

```
@staticmethod
def GetSomething(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
```

Take a look at generated *_grpc.py file. You have inside 3 classes: client API - *Stub, server API - *Servicer, and some other API marked as experimental. Indeed the last one is not yet supported. My question, are you really using it? Is it still experimental or mature enough for production?

**Comment by gitpushdashf** [comment]
Thank you for looking into this! I think I mistakenly forgot to note that GetSomething is part of the service stub.

This is how we've been doing things in production, although about to merge the latest mypy-protobuf updates where we had to `# type: ignore` those lines.

You can see here that UnaryUnaryMultiCallable has request, timeout, metadata, etc: https://grpc.github.io/grpc/python/grpc.html#grpc.UnaryUnaryMultiCallable

While request seems to be handled in the .pyi, metadata is not.

I hope this makes sense. I am definitely not a gRPC expert.

**Comment by alkasm** [comment]
@gitpushdashf What you are asking for is already in master, just not in a release yet. As @Evgenus said, the gRPC stub methods are now annotated with the MultiCallable interface in master, due to the PR I linked above. You should be able to verify that you can get rid of your `# type: ignore` comments if you install the latest master.

@Evgenuswhen do you know when we would be likely to see a 2.4.1 or 2.5 cut? I'm not sure on your release cadence or process, just would like to use this soon 😄

**Comment by gitpushdashf** [comment]
Ah, I understand. Thank you!

**Comment by nipunn1313** [comment]
I'll do a release at some point in the next couple of weeks! Just gotta do some additional testing.

In the meantime, you can install unreleased version (instructions are available in the README on the main page)

**Comment by mr-bjerre** [comment]
Hi all and thanks for a great plugin.

I'm not sure if this is related or not. But I don't get the typings for `request` and `context` in the server API  (*Servicer). although it looks right in *_grpc.pyi

```python
class RouteGuideServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetFeature(self,
        request: global___Point,
        context: grpc.ServicerContext,
    ) -> global___Feature: ...
```

I might be mistaken but shouldn't I get code completion for e.g. `request` when implementing `RouteGuideServicer.GetFeature`? I use vscode btw. (pylance). Mypy passes....

**Comment by nipunn1313** [comment]
I'm not familiar with vscode/pylance/pyright with regard to this grpc plugin - you're welcome to debug further and report back with any findings.

**Comment by mr-bjerre** [comment]
Fair! I'm not really sure where to get started but I'll try. 

But maybe you can answer a more general question; is it possible to get code completion / suggestions for request etc.?

**Comment by nipunn1313** [comment]
Sounds like you want some kind of code autocompletion?

Unfortunately, don't really have context on that. mypy-protobuf provides type stubs - autocompletion is a separate system entirely. I know that the pyright maintainer has perused through here in the past - but perhaps if you are using pyright you can follow up over there.

**Comment by Evgenus** [comment]
https://stackoverflow.com/questions/53578365/does-vscode-support-python-pyi-files-for-intellisense
I think you can start with that.

I, personally, stopped using VSC in favor of PyCharm. But I remember that I was not happy with auto-completion as well.

**Comment by nipunn1313** [comment]
I looked through this.

Generated stubs for `DummyService` are here
https://github.com/dropbox/mypy-protobuf/blob/master/test/generated/testproto/grpc/dummy_pb2_grpc.pyi.expected

It contains `DummyServiceStub`, and `DummyServiceServicer`, but not `DummyService`

`DummyService` is [generated](https://github.com/grpc/grpc/blob/master/src/compiler/python_generator.cc#L591) like this:
```
 # This class is part of an EXPERIMENTAL API.
class DummyService(object):
```

As @Evgenus mentioned, it's not mentioned in the docs
https://grpc.io/docs/languages/python/generated-code/

For now, I'm going to close this. I'm open to typing undocumented things - but only if we're working with someone with some inside roadmap knowledge of GRPC. For now, I will close this.
