### ISSUE TITLE
Eliminate type-ignore that's generated for enums (allowing us to eliminate warn_unused_ignores = False in mypy.ini)

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/mypy-protobuf#239]
Per discussion in #214 - see if we can eliminate the type-ignore that's generated for enums

It exists to sidestep the circular dependency that our enum strategy creates. In order to use the alternate strategy of pulling the type definition up one level, we need type aliases to work within a class - see https://github.com/python/mypy/issues/10788

**Comment by pcorpet** [comment]
`mypy` seems to manage the type properly and thus is raising a
```sh
error: unused "type: ignore" comment
```

Do you know a way for comments to only be used by `pyright`? or do you recommend to disable the warnings in `mypy`? (`--no-warn-unused-ignores`) although that would mean to remove it for all other warnings :-(

**Comment by nipunn1313** [comment]
The technique I used was to update mypy.ini via the same technique as in #237
