### ISSUE TITLE
grpcio-tools version pinned

### ISSUE THREAD

**Issue by Tenzer** [dropbox/mypy-protobuf#264]
Hi. I noticed version 2.8 now pins the grpcio-tools package version to version 1.38.1, that means we can't use mypy-protobuf together with the latest version of grpcio-tools which is version 1.39.0.

The [README file](https://github.com/dropbox/mypy-protobuf#to-run-mypy-on-code-generated-with-grpc-plugin---youll-additionally-need) states:

> To run mypy on code generated with grpc plugin - you'll additionally need
> 
> grpcio>=1.38.1 grpcio-tools>=1.38.1 grpc-stubs>=1.24.6

it's however not possible to install a newer version of grpcio-tools than 1.38.1 due to the exact version pinning used in `setup.py`:

https://github.com/dropbox/mypy-protobuf/blob/c7d02940bff0b0b1db1090d8b7b1b415ffffdc0f/setup.py#L33

Should that dependency definition instead be changed to use `>=` rather than `==`?

**Comment by pcorpet** [comment]
Same thing is true for `types-protobuf`. mypy-protobuf v2.8 has it pinned at `3.17.3` whereas there's a new version at `3.17.4`...

**Comment by nipunn1313** [comment]
I can make that change to do my best to make it work more easily out of box
without a venv.

Thanks for the feedback!

But generally speaking, the requirements to run mypy-protobuf itself aren’t
necessarily going to be the same as running mypy on the generated code.

To avoid this problem permanently, install/run mypy-protobuf in a venv
separate from the one which you run mypy from.

Eg

python3 -m venv mp_venv
mp_venv/bin/python -m pip install mypy-protobuf
mp_venv/bin/protoc-gen-mypy

—Nipunn

**Comment by nipunn1313** [comment]
Making the dependency loose runs the risk of having future changes to those
two packages break mypy-protobuf in the future, but given the commonality
of trying to run it out of the same python installation, I suppose we can
take that risk.

Dependencies dependencies

**Comment by nipunn1313** [comment]
Going to switch to >=.

If we get bitten by the "mypy-protobuf randomly broke because of an upstream change to grpcio-tools" then - might consider walking this back and instead recommending use of venvs when using mypy-protobuf.
