### ISSUE TITLE
Cannot instantiate abstract class with abstract attribute 

### ISSUE THREAD

**Issue by gitpushdashf** [dropbox/mypy-protobuf#266]
After updating to the latest version for #212, I started getting a new error with mypy --strict.

`error: Cannot instantiate abstract class "Servicer" with abstract attribute "GetThing"`

I don't have a reduced test case for this yet, but thought someone might have an idea of what might be causing it.

**Comment by nipunn1313** [comment]
Thanks for the report

Do you have a concrete reproable example? Hard to understand without knowing what Servicer and GetThing are in this context. At least at a glance without further context, it might appear that the error is legitimate (IE need to define GetThing)

We have a test here which doesn't run into any issue
https://github.com/dropbox/mypy-protobuf/blob/main/test/test_grpc_usage.py

**Comment by nipunn1313** [comment]
BTW - There were no changes made related to #212

**Comment by nipunn1313** [comment]
Closing from inactivity - feel free to reopen with more information.
