### ISSUE TITLE
Improve copying of comments

### ISSUE THREAD

**Issue by jaredkhan** [dropbox/mypy-protobuf#280]
In https://github.com/dropbox/mypy-protobuf/commit/eb1defa98654832732368ee4247009212d337567, comments from the .proto files were copied over into the type stubs.

The comments in the .proto files I'm using are intended to be docstrings, but mypy-protobuf writes them out to the .pyi files using `#` rather than `"""`, and before message classes rather than on the first line of the class body, so they are not treated as docstrings and so don't show up in the documentation view of the IDE I am using (PyCharm 2021.2).

i.e. I would prefer:

```
# My leading detached comments
class Foo(google.protobuf.message.Message):
    """My leading comments

    My trailing comments
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ...
```

rather than the current situation of:

```
# My leading detached comments
# My leading comments
# My trailing comments
class Foo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
```

This convention of documentation as a docstring on the first line of the class seems to me to be common enough to justify the suggested pattern. Since there is less of a prevailing convention for how to document attributes of a Python class, I think the current situation (a # comment before the field attribute) is okay for field comments.

**Comment by nipunn1313** [comment]
Yep agreed! I admit I thought about this in the initial implementation, but ended up doing it this way as a first pass implementation because it was easier (They all use a single helper that uses `#` comments).

**Comment by nipunn1313** [comment]
Didn't end up being as tough as expected! Take a look at #281 if you get the chance @jaredkhan . Thanks for the report.
