### ISSUE TITLE
relative imports are not supported

### ISSUE THREAD

**Issue by ierezell** [dropbox/mypy-protobuf#304]
When using `-I` to import other proto files (common declaration in my use-case) the python generated file does not import correctly the  generated file. 

E.g : 

```
makefile
A 
--- A.proto
Common
--- common.proto
```

In the makefile : 
```
./protoc/bin/protoc  -I Common -I A
	--python_out=$(COMPILED_PROTO_DIRECTORY) \
	--mypy_out=$(COMPILED_PROTO_DIRECTORY) \
	--grpc_out=$(COMPILED_PROTO_DIRECTORY) \
	--mypy_grpc_out=$(COMPILED_PROTO_DIRECTORY) \
	A/A.proto
```

Which generate a file (a_pb2.py) with : 

```python
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import common_pb2
```

However `common_pb2` is not a module in my path ! At least it should be `from common import common_pb2` (which would in my case work)

I know it's a known problem but using https://github.com/danielgtaylor/python-betterproto seems to fix it (however it comes with other things I don't want and seems less maintained than  this repo)

Do you have any fix / advice 

Thanks in advance
Have a great day

**Comment by cpcloud** [comment]
Another option is to use the tool I built (https://github.com/cpcloud/protoletariat) to automatically rewrite the protobuf imports to relative imports. The tool rewrites imports using FileDescriptorSets, so it's aware of the generated code's structure.
