### ISSUE TITLE
Generated types do not respect optional keyword.

### ISSUE THREAD

**Issue by fahadkh** [dropbox/mypy-protobuf#315]
I'm trying to understand why the [`optional` keyword](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3) has no impact on my generated types. My understanding for proto3 is that the `optional` keyword should allow us to explicitly set the value of the field to null over the wire. However, given the following `.proto` file:  

```proto3
syntax = "proto3";

message Term {
  string id = 1;
  string name = 2;
  optional string parent = 3;
}
```

I would expect the following types on `Term.__init__()`:

```python
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        parent : typing.Optional[typing.Text] = ...
    )
```

However the actual result does not allow us to set the `optional` `parent` field to `None`:

```python
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        parent : typing.Text = ...
    )
```

when `relax_strict_optional_primitives` is set, all the fields become optional:

```python
    def __init__(self,
        *,
        id : typing.Optional[typing.Text] = ...,
        name : typing.Optional[typing.Text] = ...,
        parent : typing.Optional[typing.Text] = ...
    )
```

Shouldn't the output use the [`optional` keyword from the `.proto` file](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3) to determine if a field should be considered optional? That way the type checker can  determine whether the omission was intentional or not per the `.proto` specification. 

Edit: [I'm seeing that this should be the case](https://github.com/dropbox/mypy-protobuf/pull/157/files). Perhaps i'm using arguments incorrectly.

**Comment by goffrie** [comment]
Field presence for proto3 hasn't been implemented yet, it's a newish feature.

**Comment by nipunn1313** [comment]
I think it's updated on master - but hasn't been released yet. What version are you using?

https://github.com/dropbox/mypy-protobuf/blob/main/CHANGELOG.md

We added support around a year ago for field presence, but in the constructor I believe it was only added with #310 recently

**Comment by fahadkh** [comment]
Ah ok, thank you. I'm on version 3.0.0 - Looks like field presence is working as described and I'm just missing the Optional type in the constructor which is not yet released.
