### ISSUE TITLE
Import for standard protobuf formats is wrong

### ISSUE THREAD

**Issue by nmiculinic** [dropbox/mypy-protobuf#4]
Generates:

```python 
from google.protobuf.timestamp import (
    Timestamp,
)
```

and it should be:
```python
from google.protobuf.timestamp_pb2 import (
    Timestamp,
)
```

similarly for other standard types:
```python
from google.protobuf.empty_pb2 import (
    Empty,
)
```

**Comment by gvanrossum** [comment]
Is that with the Go or the Python toolchain?

Can you easily fix the problem? If so, I recommend submitting a PR with the fix!

**Comment by nmiculinic** [comment]
Python tooling.. I think it's an easy fix. Will do when I find some time, in a few days hopefully. For now I've fixed internally with sed (there are other places where standard python generation has some issues)

**Comment by gvanrossum** [comment]
Thanks for your help!

**Comment by nipunn1313** [comment]
Thanks @nmiculinic
