### ISSUE TITLE
Mypy currently does not support module import references

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/mypy-protobuf#41]
eg
```
import dropbox.proto.nucleus.types_pb2
from dropbox.proto.nucleus.types_pb2 import FileId
reveal_type(FileId)
reveal_type(dropbox.proto.nucleus.types_pb2.FileId)
```

results in
```
dropbox/proto/nucleus/app_service_pb2.pyi:17: error: Revealed type is 'def (id: Union[builtins.str, None] =) -> dropbox.proto.nucleus.types_pb2.FileId'
dropbox/proto/nucleus/app_service_pb2.pyi:18: error: Revealed type is 'Any'
```

Proposed workaround is:
```
from dropbox.proto.nucleus.types_pb2 import FileId as dropbox___proto___nucleus___types_pb2___FileId
```

Until mypy gains support for module imports like this (see https://github.com/python/mypy/issues/5583).

**Comment by gvanrossum** [comment]
Can you cross link this with the issue on mypy?

**Comment by vmagamedov** [comment]
@nipunn1313 Hi! I can't reproduce your case, I'm using `mypy==0.630` on Python 3.7.0, and here is what I get:
```python
# file: example/helloworld/helloworld_pb2.pyi
import google.protobuf.any_pb2
from google.protobuf.any_pb2 import Any

reveal_type(google.protobuf.any_pb2.Any)
reveal_type(Any)
```

```
$ MYPYPATH=example mypy -m helloworld.client
example/helloworld/helloworld_pb2.pyi:6: error: Revealed type is 'def (type_url: Union[builtins.str, None] =, value: Union[builtins.bytes, None] =) -> google.protobuf.any_pb2.Any'
example/helloworld/helloworld_pb2.pyi:7: error: Revealed type is 'def (type_url: Union[builtins.str, None] =, value: Union[builtins.bytes, None] =) -> google.protobuf.any_pb2.Any'
```

`mypy==0.620` also works. `mypy==0.610` doesn't have `google.protobuf` stubs in the typeshed.

I was wondering why mypy-protobuf is using such mangled imports in generated files, maybe I missed something?

**Comment by nipunn1313** [comment]
Hi! Thanks for the comment.

Interestingly, I also don't repro using your example, but I do repro with mine, so they must be subtly different:

```
import google.protobuf.empty_pb2
from google.protobuf.empty_pb2 import Empty
import dropbox.proto.nucleus.types_pb2
from dropbox.proto.nucleus.types_pb2 import FileId

reveal_type(google.protobuf.empty_pb2.Empty)
reveal_type(Empty)
reveal_type(FileId)
reveal_type(dropbox.proto.nucleus.types_pb2.FileId)
```
```
dropbox/proto/nucleus/app_service_pb2.pyi:71: error: Revealed type is 'def () -> google.protobuf.empty_pb2.Empty'
dropbox/proto/nucleus/app_service_pb2.pyi:72: error: Revealed type is 'def () -> google.protobuf.empty_pb2.Empty'
dropbox/proto/nucleus/app_service_pb2.pyi:73: error: Revealed type is 'def (id: Union[builtins.str, None] =) -> dropbox.proto.nucleus.types_pb2.FileId'
dropbox/proto/nucleus/app_service_pb2.pyi:74: error: Revealed type is 'Any'
```

Perhaps it must be an import to another pyi file?

I actually landed #42 to `mypy-protobuf` to add name mangling to mitigate this issue. We had cases where different modules had messages of the same names. In order to import both of them, we either needed fully qualified imports (which weren't working due to this issue), or mangled from-style imports.

I would be excited to switch back to non-mangled fully qualified imports once the upstream mypy issue is solved.

**Comment by vmagamedov** [comment]
I've tried to fully simulate your case, so in my example `example/helloworld/helloworld_pb2.pyi` should import `mypy/typeshed/third_party/2and3/google/protobuf/any_pb2.pyi`. Maybe there is something suspicious in your `dropbox/proto/nucleus/types_pb2.pyi`?

**Comment by nipunn1313** [comment]
try importing something that's not in typeshed.

Eg.

`example/helloworld/helloworld.proto`
`example/helloworld/greetings.proto`

with helloworld.proto importing from greetings.proto

If that also works, that'll rule out the hypothesis that typeshed is making a difference.

**Comment by vmagamedov** [comment]
Added `helloworld/helloworld2.proto` file with `import "helloworld/helloworld.proto";`

Then in generated `helloworld/helloworld2_pb2.pyi` added:
```python
from helloworld.helloworld_pb2 import (
    HelloReply as helloworld___helloworld_pb2___HelloReply,
    HelloRequest as helloworld___helloworld_pb2___HelloRequest,
)
import helloworld.helloworld_pb2
reveal_type(helloworld.helloworld_pb2.HelloReply)
reveal_type(helloworld___helloworld_pb2___HelloReply)
```
and result is the same
```
example/helloworld/helloworld2_pb2.pyi:20: error: Revealed type is 'def (message: Union[builtins.str, None] =) -> helloworld.helloworld_pb2.HelloReply'
example/helloworld/helloworld2_pb2.pyi:21: error: Revealed type is 'def (message: Union[builtins.str, None] =) -> helloworld.helloworld_pb2.HelloReply'
```

**Comment by nipunn1313** [comment]
Interesting. There must be something unique about my setup, causing the
issue. Will have to do some work to narrow it down
--Nipunn

**Comment by nipunn1313** [comment]
was unable to repro
