### ISSUE TITLE
What is the minimum proto version and python version needed?

### ISSUE THREAD

**Issue by debraj-manna** [dropbox/mypy-protobuf#43]
On trying to use this with proto 2.5.0 and python 2.7 I am getting the below error

```
  [exec] Traceback (most recent call last):
     [exec]   File "/Users/dmanna/Documents/fresh_code/github/vnera/main/main/venv/bin/protoc-gen-mypy", line 364, in <module>
     [exec]     main()
     [exec]   File "/Users/dmanna/Documents/fresh_code/github/vnera/main/main/venv/bin/protoc-gen-mypy", line 351, in main
     [exec]     generate_mypy_stubs(Descriptors(request), response, "quiet" in request.parameter)
     [exec]   File "/Users/dmanna/Documents/fresh_code/github/vnera/main/main/venv/bin/protoc-gen-mypy", line 293, in generate_mypy_stubs
     [exec]     pkg_writer.write_messages(fd.message_type, "")
     [exec]   File "/Users/dmanna/Documents/fresh_code/github/vnera/main/main/venv/bin/protoc-gen-mypy", line 169, in write_messages
     [exec]     if msg.options.map_entry:
     [exec] AttributeError: 'MessageOptions' object has no attribute 'map_entry'
     [exec] --mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
     [exec] Result: 1

```

- Proto Version - 2.5.0
- Python Version - 2.7.6

**Comment by nipunn1313** [comment]
Hi - great question.
We haven't been super rigorous on testing with a bunch of versions unfortunately.

Here - we apt-get install the ubuntu protobuf-compiler and run with both python 2.7 and 3.5, though I am not sure which minor version is tested.

https://github.com/dropbox/mypy-protobuf/blob/master/.travis.yml

I will add some logging to print out the versions that we're testing with travis.

**Comment by debraj-manna** [comment]
Thanks for replying.

What was the version of Ubuntu?

**Comment by nipunn1313** [comment]
map_entry is provided here
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L495

According to the changelog, this was added in 3.0.0
https://github.com/protocolbuffers/protobuf/blob/master/CHANGES.txt#L1290

**Comment by nipunn1313** [comment]
I updated the README with the new findings of requirements
If you need protoc 2.5 support, pop open a new issue with it as a feature request with some context as to why upgrading is a challenge.

Hopefully that's helpful! If you have any questions, leave a note here.
