### ISSUE TITLE
Doesn't work with `--grpc_python_out`

### ISSUE THREAD

**Issue by samuela** [dropbox/mypy-protobuf#45]
The plugin runs fine for pure protobuf files, but it seems to trip up when using gRPC:

```
(venv) python [master ?] -> protoc -I../protos --python_out=. --grpc_python_out=. --mypy_out=. ../protos/pingpong.proto
protoc-gen-grpc_python: program not found or is not executable
--grpc_python_out: protoc-gen-grpc_python: Plugin failed with status code 1.
```

**Comment by samuela** [comment]
Here's my proto file in case that's of interest:

```proto
syntax = "proto3";

package pingpong;

service PingPongPlayer {
  rpc Play (PlayRequest) returns (PlayReply) {}
}

message PlayRequest {
  int64 count = 1;
}

message PlayReply {
  int64 count = 1;
}
```

**Comment by nipunn1313** [comment]
Hi - thanks for the report samuela.

Do you know what the errors are specifically? Does it provide any additional output?
The plugins are generally independent, so this at a glance looks like a failure of the `protoc-gen-grpc_python`, but it is possible I'm missing some detail.

Some things to try on your sample file to narrow down issue
1) Run just mypy-protobuf `protoc -I../protos --python_out=. --mypy_out=. [rest of args]`
2) Run just python out `protoc -I../protos --python_out=.`
3) Run just grpc `protoc -I../protos --python_out=. --grpc_python_out=.`

Which ones work and which don't? Are there any additional logs in the error messages?

**Comment by samuela** [comment]
Here's exactly what I get for each of those commands:

```
(venv) python [master] -> protoc -I../protos --python_out=. --grpc_python_out=. --mypy_out=. ../protos/pingpong.proto
protoc-gen-grpc_python: program not found or is not executable
--grpc_python_out: protoc-gen-grpc_python: Plugin failed with status code 1.
(venv) python [master] -> protoc -I../protos --python_out=. --mypy_out=. ../protos/pingpong.proto
Writing mypy to pingpong_pb2.pyi
(venv) python [master ?] -> protoc -I../protos --python_out=. ../protos/pingpong.proto
(venv) python [master ?] -> protoc -I../protos --python_out=. --grpc_python_out=. ../protos/pingpong.proto
protoc-gen-grpc_python: program not found or is not executable
--grpc_python_out: protoc-gen-grpc_python: Plugin failed with status code 1.
(venv) python [master ?] -> 
```

So it looks like this is an issue with protoc-gen-grpc_python and not mypy-protobuf then. I found that the grpc_tools python package doesn't override `protoc`, so it was using the system `protoc`. My solution was to use 
```
python -m grpc_tools.protoc -I../protos --python_out=. --grpc_python_out=. --mypy_out=. ../protos/pingpong.proto
```
