### ISSUE TITLE
Mypy errors out on enum and nested types (they are mis-annotated?)

### ISSUE THREAD

**Issue by abhishekrb19** [dropbox/mypy-protobuf#56]
I noticed `mypy` check fails on enum and nested types usage. I tweaked the `test_generated_mypy.py` to minimally reproduce the issue. 

[https://github.com/dropbox/mypy-protobuf/blob/master/test/test_generated_mypy.py#L52](https://github.com/dropbox/mypy-protobuf/blob/master/test/test_generated_mypy.py#L52
)

Passing an enum instead:

`s = Simple1(a_enum=1)
`

The example runs fine though, but `mypy` complains of incompatible type. Please see error below:

```
mypy --py2 test/test_generated_mypy.py
```
> test/test_generated_mypy.py:70: error: Argument "a_enum" to "Simple1" has incompatible type "int"; expected "Optional[OuterEnum]"

Please see the type hint here:
https://github.com/dropbox/mypy-protobuf/blob/master/test/proto/test_pb2.pyi.expected#L126

Should the type hint say `int` (or `str`?) instead of the enum type (`OuterEnum` here)? Or am I missing something here?

**Comment by nipunn1313** [comment]
Aha - I was also able to reproduce
We designed mypy-protobuf to cover this more common case:

```
from test.proto.test_pb2 import FOO
...
s = Simple1(a_enum=FOO)
```

However, the case you described (passing the int in directly) is also totally viable - so we need to cover that as well.

For reference - OuterEnum is defined as such (subclassed from `int`)
```
class OuterEnum(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[int]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, int]]: ...
FOO = typing___cast(OuterEnum, 1)
BAR = typing___cast(OuterEnum, 2)
```

One possibility is that we could annotate as `Optional[Union[OuterEnum, int]]`
Another possibility is is to be more opinionated and force people using the library to use `FOO` and `BAR` or do some explicit casting (eg `typing.cast(OuterEnum, 1)`)
Another idea (not sure if it's possible) is to inform Mypy that ints should be seamlessly castable to OuterEnums

@gvanrossum - do you have any recommendation here?

**Comment by pcorpet** [comment]
I think it's worth being opinionated here: `s = Simple1(a_enum=42)` is not valid (as there are no enum value with 42) and I think it's worth mentioning it early. The workaround (`typing.cast`) seems pretty easy and have the benefit of making it explicit.

Note that this "feature" actually helped us find a bug in our code last week.

**Comment by nipunn1313** [comment]
I actually think we're able to get best of both worlds here by using the mypy Literal type. This way, the typing will be indeed an int, but the int is constrained to only the legitimate values.

https://mypy.readthedocs.io/en/latest/literal_types.html
Putting up a diff in a moment with a proposal.
