### ISSUE TITLE
mypy import RepeatedScalarFieldContainer, not found

### ISSUE THREAD

**Issue by selimyoussry** [dropbox/mypy-protobuf#7]
Hey guys, great work! This is already really helpful, thanks :).

I am having an issue with the generated code for `repeated` fields, I see you are using `RepeatedScalarFieldContainer` from `mypy`, but with version 0.560, I can't find it. Which version of `mypy` were you using for this to work?

For the record, in `myproto_pb2.pyi`, I am talking about the import
```python
from mypy import (
    RepeatedScalarFieldContainer,
)
```

Thank you

**Comment by nipunn1313** [comment]
Hi @selimyoussry.

Thanks for the report. I'm looking into it.

**Comment by nipunn1313** [comment]
Hm, this is a great find.

These stubs are intended to be in typeshed, but we overlooked this dependency when open sourcing this. At Dropbox, we had a fork of this pull request sitting in our repo at mypy/

Here's the outstanding pull request to add this to typeshed.
https://github.com/python/typeshed/pull/1718

I'll work on making sure this gets through, and update the type to rely on variant in typeshed

**Comment by nipunn1313** [comment]
I updated https://github.com/python/typeshed/pull/1718, so I'm just waiting on that to come through. Then I'll update the generated code here to reference it.

As a shorter term workaround (if you need something sooner), you can grab the containers.pyi from that pull request and drop it in a mypy/ package.

**Comment by nipunn1313** [comment]
Ok @selimyoussry - I've gotten the upstream fix into typeshed, and punched in the fix here. Let me know if there are any further issues!

Again, thanks for the report!

**Comment by selimyoussry** [comment]
Thanks @nipunn1313 it seems to work now!
