### ISSUE TITLE
Syntax error output if a field is named 'from'

### ISSUE THREAD

**Issue by gaggle** [dropbox/mypy-protobuf#73]
This tool generates .pyi files with syntax error when parsing a proto-file with a field named `from`. E.g. `foo.proto`:
```
message FooRequest {
	int64 from = 5;
}
```

Running mypy on a project with this kind of autogenerated files results in syntax error:
```
$ mypy
package/schemas/foo_pb2.pyi:356: error: invalid syntax
```

This is because the `foo_pb2.pyi` file has this in it:
```
class FooRequest(google___protobuf___message___Message):
    from = ... # type: int
```

The `from = ...` is invalid syntax, and so we have a problem.

Just to say I've set up my mypy to ignore these files, `mypy.ini`:
```
[mypy]

[mypy-package.schemas.*]
ignore_errors = True
```

But this doesn't ignore syntax errors. As per https://github.com/python/mypy/issues/6897 mypy **can't** ignore syntax errors. It would be favorable if this project did not generate syntax-invalid output.

I'm using versions:
```
$ python --version Python 3.6.7
mypy==0.701
mypy-protobuf==1.10
```

And here is a gist with the entire contents of the `.proto` file, the generated `.py` file (which does not have syntax errors and the problematic and unexcludable `.pyi` file:
https://gist.github.com/gaggle/8aef6102d314936c9eb33724194682b0

**Comment by nipunn1313** [comment]
Great bugreport! Thanks.

I don't know offhand how we're supposed to type a variable with a reserved keyword name. Will look into it w/ mypy docs / folks. Thanks for reporting!

**Comment by gvanrossum** [comment]
It looks like the .py file generator sidesteps the issue by not generating Python code but some meta thing. So at runtime you'd have to write `getattr(thing, 'from')`. (And add `# noqa` :-)

Since there can't be any code that writes `thing.from`, maybe the simplest thing would be to just not emit the field at all? Or perhaps emit it with a `#` in front of it?

**Comment by ikonst** [comment]
I'd not emit them. See also https://developers.google.com/protocol-buffers/docs/reference/python-generated#keyword-conflicts
