### ISSUE TITLE
Invalid syntax error in generated .pyi file

### ISSUE THREAD

**Issue by burk** [dropbox/mypy-protobuf#80]
Hey! I've started using your plugin, and it's working to an extent that the type hints are picked up by my IDE, which is helpful.

When trying to run mypy on the command line I get this error however:
```
com/fish/time/time_range_pb2.pyi:45: error: invalid syntax
```

The relevant lines:
```
 42 class TimeRange(google___protobuf___message___Message):
 43 
 44     @property
 45     def from(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
 46 
```

I'm using this command line to check the types:
```
mypy --ignore-missing-imports --python-version 3.7 --namespace-packages --check-untyped-defs -p fish
```
where the `com` and `fish` directories reside inside the same directory, and `fish` is importing protobufs from `com`.

Before adding the `--namespace-packages` mypy did finish, but it didn't seem like it took the types of the protobufs into account.

The protobufs are generated by
```
python3 -m grpc_tools.protoc -I ./proto --python_out=. --mypy_out=. --grpc_python_out=. ./proto/com/fish/*/*.proto
```

mypy version 0.701, Python 3.7.3

Any ideas?

**Comment by nipunn1313** [comment]
Hi!
Thank you for the report. This was actually only very-recently fixed with #73 - since `from` is a python literal - we can't actually type messages with a message name `from` effectively. Look out for a new release of mypy-protobuf shortly

Once it's out, you can do `pip install --upgrade mypy-protobuf` to pick it up.

**Comment by burk** [comment]
Ah, I see. Looking forward to the next release!

**Comment by burk** [comment]
Strange.. I'm still seeing this issue even with the latest mypy-protobuf

```
(python) 0 burk@banach:~/dev/fish/python [pipenv-install] > pip3 show mypy-protobuf
Name: mypy-protobuf
Version: 1.14
Summary: Generate mypy stub files from protobuf specs
Home-page: https://github.com/dropbox/mypy-protobuf
Author: Nipunn Koorapati
Author-email: nipunn@dropbox.com
License: Apache License 2.0
Location: /home/burk/.local/share/virtualenvs/python-C9NY5XeG/lib/python3.7/site-packages
Requires: protobuf
Required-by: 
(python) 0 burk@banach:~/dev/fish/python [pipenv-install] > mypy --ignore-missing-imports --python-version 3.7 --namespace-packages --check-untyped-defs -p fish
com/fish/time/time_range_pb2.pyi:45: error: invalid syntax
(python) 0 burk@banach:~/dev/fish/python [pipenv-install] > sed -n 45p com/fish/time/time_range_pb2.pyi 
    def from(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
(python) 0 burk@banach:~/dev/fish/python [pipenv-install] > 
```

Maybe I'm doing something very stupid. I'll try to create a minimal example and push it somewhere.

**Comment by burk** [comment]
With the new release I'm having the same issue with the `class` keyword.

**Comment by nipunn1313** [comment]
woops! It appears to be missing from
https://github.com/dropbox/mypy-protobuf/blob/master/python/protoc-gen-mypy#L44

Comparing to https://www.programiz.com/python-programming/keyword-list - it's the only one missing. Going to go ahead and add it and kick a version of mypy-protobuf! Thanks for the catch!

**Comment by nipunn1313** [comment]
#91 should solve it!
