### ISSUE TITLE
Plugin doesn't support all type of notations for accessing Enum values

### ISSUE THREAD

**Issue by Kami** [dropbox/mypy-protobuf#82]
Currently it appears that this plugin doesn't support all type of notations for accessing Enum values.

Example protobuf definition (``execution.proto``):

```protobuf
enum ExecutionStatus {
    REQUESTED = 0;
    SCHEDULED = 1;
    RUNNING = 2;
    SUCCEEDED = 3;
    FAILED = 4;
    TIMED_OUT = 5;
    CANCELED = 6;
}
```

Right now, the following ways to refer to the enum value work and don't result in a mypy error:

```python
import execution_pb2

execution_pb2.REQUESTED
execution_pb2.Value('REQUESTED')
...
```

The problem is that the following more verbose approach (where you access the value via enum type class) returns an error:

```python
execution_pb2.ExecutionStatus.REQUESTED
```

```bash
foo.py: error: "Type[ExecutionStatus]" has no attribute "SUCCEEDED"
```

This approach is supported by the protobuf generated Python code. I also personally prefer it since it's more explicit and obvious when there are multiple top-level enum types defined in a single proto file.

Using ``Value('')`` method is also not desired since it doesn't provide any static typing guarantees - if you pass in an invalid / unsupported value, this will only be detected during run-time.

I checked the generated annotations file and it looks like it only writes type hints for accessing enum values via global module level variables.

From the generated type hints code:

```python
class ExecutionStatus(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> ExecutionStatus: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[ExecutionStatus]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, ExecutionStatus]]: ...
REQUESTED = typing___cast(ExecutionStatus, 0)
SCHEDULED = typing___cast(ExecutionStatus, 1)
RUNNING = typing___cast(ExecutionStatus, 2)
SUCCEEDED = typing___cast(ExecutionStatus, 3)
FAILED = typing___cast(ExecutionStatus, 4)
TIMED_OUT = typing___cast(ExecutionStatus, 5)
CANCELED = typing___cast(ExecutionStatus, 6)
```

I propose to update it so it looks like this:

```python
class ExecutionStatus(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> ExecutionStatus: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[ExecutionStatus]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, ExecutionStatus]]: ...
    REQUESTED = typing___cast(ExecutionStatus, 0)
    SCHEDULED = typing___cast(ExecutionStatus, 1)
    RUNNING = typing___cast(ExecutionStatus, 2)
    SUCCEEDED = typing___cast(ExecutionStatus, 3)
    FAILED = typing___cast(ExecutionStatus, 4)
    TIMED_OUT = typing___cast(ExecutionStatus, 5)
    CANCELED = typing___cast(ExecutionStatus, 6)

REQUESTED = typing___cast(ExecutionStatus, 0)
SCHEDULED = typing___cast(ExecutionStatus, 1)
RUNNING = typing___cast(ExecutionStatus, 2)
SUCCEEDED = typing___cast(ExecutionStatus, 3)
FAILED = typing___cast(ExecutionStatus, 4)
TIMED_OUT = typing___cast(ExecutionStatus, 5)
CANCELED = typing___cast(ExecutionStatus, 6)
```

This way those values can be access using both supported way - directly via top level variable or via enum class level variable.

Somewhat related issue #56.

**Comment by Kami** [comment]
EDIT: It looks like an issue / PR for that already exists - #81.

I only noticed it when I started to work on the change to support this myself. Sorry for the duplicate, we can continue in #81.

**Comment by nipunn1313** [comment]
Thanks for the report @Kami !
