### ISSUE TITLE
Add `protobuf` to setup.py 

### ISSUE THREAD

**Issue by gtalarico** [dropbox/mypy-protobuf#86]
When using mypy-protobuf, the plugin expects `pypi/protobuf` to be installed.
If it's not, the build fails:
```
Traceback (most recent call last):
  File "/Users/gui_talarico/dev/repos/samara/by-schema/.venv/bin/protoc-gen-mypy", line 13, in <module>
    import google.protobuf.descriptor_pb2 as d
ModuleNotFoundError: No module named 'google'
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```

If `protobuf` pkg is required, seems to me we could just add it to `setup.py` so the dependency is automatically when `mypy-protobuf` is installed

Thoughts? 

```python
# setup.py
setup(
    install_requires=["protobuf"],
    # ...
)
```

**Comment by nipunn1313** [comment]
Thanks for the report! Good idea.
