### ISSUE TITLE
Incompatible types in assignment (x: SomeMessage = Message)

### ISSUE THREAD

**Issue by DaniGuardiola** [dropbox/mypy-protobuf#97]
I have the following code:

```python
from proto.example_pb2 import SomeMessage
from google.protobuf.message import Message


def request(...) -> Message:
	...

result: SomeMessage = request(
    ...
)
```

Request will return a protobuf message which can vary depending on the input parameters. This is giving the following mypy error:

```
error: Incompatible types in assignment (expression has type "Message", variable has type "SomeMessage")
```

Now, I understand why this is happening: `Message` is not assignable to `SomeMessage`. It would be valid the other way around (`SomeMessage` -> `Message`) because `SomeMessage` is a subclass of `Message`.

The reasoning behind this code is that while `request` can return any message, when I use it I already know which specific message it will return, and I want to be able to type it like this. I just don't know how to go about it.

The only solution I thought about is to use `@overload` with some `Literal` types to set the return of every message type, as it really only depends on the value a string parameter, but it seems a bit overkill. I have some other situations in my code where this happens (even without protobuf) so what I'm really asking is for help on what pattern I should be using in these kind of situations, because I'm all out of ideas.

Can anyone help me figure this out?

Thanks :)

**Comment by nipunn1313** [comment]
There exists a cast method in the typing module which might allow you to force a conversion like this.

Generally speaking, a single method  that could return a variety of types based on the input - is not a strongly typed method - so you will have to cast. The input string is “stringly typed” encoding the type in a way that bypasses the type system.

 One pattern might be to have N typed methods (either with overload like you mention - or even N methods with different names that don’t require arguments).

**Comment by nipunn1313** [comment]
You may be able to ask a similar question in the mypy repo to get more eyes on it for possible alternatives.

**Comment by ikonst** [comment]
If you know which message each kind of request returns, this sounds very much like [RPC services](https://developers.google.com/protocol-buffers/docs/proto#services). In such case, I would expect your RPC service (defined in Protobuf) to result in a generated Python typestub to the effect of:
```
class MyService:
   def foo(my_request: MyRequest) -> MyResult: ...
   def bar(...) -> ...: ...
```
etc.
