### ISSUE TITLE
Using within bazel?

### ISSUE THREAD

**Issue by moshe** [dropbox/mypy-protobuf#99]
Hey team🙌
I know dropbox is using Bazel and wanted to know if you can publish a BUILD file with mypy-protobuf as a dependency (go impl in better)

Thanks and really helpfull project!

**Comment by nipunn1313** [comment]
Thanks @moshe  - I think this is a better question for @dzbarsky - so shooting over.

We do use bazel, but the way it fits into our system isn't straightforward to extract directly into a BUILD file here. Would be happy to take a contribution here if you have one that works for you.

**Comment by dzbarsky** [comment]
@moshe Hi, are you looking for a build file to build the go binary itself, or a fuller integration to run the generation process within the bazel build itself (i.e. write the generated pyi files into runfiles)?

**Comment by moshe** [comment]
Hi @dzbarsky, @nipunn1313, Thank you for your time
I dug in a little deeper and ended up opening a PR for making the protobuf  python rule to accept external plugins - https://github.com/protocolbuffers/protobuf/pull/7056
But in addition, I struggled to make bazel run the go implementation due to the folder structure of the project
A BUILD example of running the go plugin will be great 🙂

**Comment by dzbarsky** [comment]
Got it. As a quick disclaimer, we actually don't use the upstream protobuf python rules, so we can't help with that bit, but it sounds like you've got it covered.

The current process of open-sourcing the go generator is pretty manual so it actually isn't fully up to date in the rep. I'm doing a bit of work today/tomorrow to improve that, after which it should show up in https://github.com/dropbox/dbx_build_tools complete with the BUILD files necessary. You should be able to add that repo as an external workspace and point to the binary rule.

Hope that's what you were looking for, and will update this thread once that's complete!

**Comment by dzbarsky** [comment]
@moshe https://github.com/dropbox/dbx_build_tools/blob/master/go/src/dropbox/build_tools/protoc-gen-mypy/BUILD is the rule we use to compile the generator. If you pull in our repo as a workspace you can refer to it as `@dbx_build_tools//go/src/dropbox/build_tools/protoc-gen-mypy`, hope that helps!

**Comment by keith** [comment]
for future readers, here's the last link of that file https://github.com/dropbox/dbx_build_tools/blob/839590cb52a6dd98376c755bb260a38f590b9210/go/src/dropbox/build_tools/protoc-gen-mypy/BUILD
